In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [ ]:
#Create a NumPy array with 10 random integers between 1 and 100.


In [71]:
x = np.random.randint(0, 100, (10))
x

array([32, 31, 74, 23, 35, 75, 55, 28, 34,  0])

In [ ]:
#Calculate the mean, median, and standard deviation of the array.


In [72]:
mean = np.mean(x)
standart_deviation = np.std(x)
median = np.median(x)

In [ ]:
#Reshape the array into a 2D matrix of shape (2, 5).


In [73]:
x = x.reshape((2,5))
x

array([[32, 31, 74, 23, 35],
       [75, 55, 28, 34,  0]])

In [ ]:
#Extract the second row of the matrix.


In [74]:
x2 = x[1,:]
x2

array([75, 55, 28, 34,  0])

In [76]:
x

array([[32, 31, 74, 23, 35],
       [75, 55, 28, 34,  0]])

In [ ]:
#Replace all odd numbers in the matrix with zeros.


In [82]:
for index, element in np.ndenumerate(x%2):
    if element != 0:
        x[index] = 0
x

array([[32,  0, 74,  0,  0],
       [ 0,  0, 28, 34,  0]])

In [96]:
x = np.random.randint(0, 100, (2,5))
x

array([[19, 46, 42, 56, 60],
       [77, 30, 24,  2,  3]])

In [ ]:
#Calculate the sum of each column in the matrix.


In [114]:
for i in range(x.shape[1]):
    subarray = x[:,i]
    print(np.sum(subarray))

96
76
66
58
63


In [ ]:
#Multiply the matrix by a scalar value of your choice.


In [127]:
x * 3

array([[ 57, 138, 126, 168, 180],
       [231,  90,  72,   6,   9]])

In [ ]:
#Calculate the dot product of the matrix with its transpose.


In [122]:
x.dot(np.transpose(x))

array([[10977,  4143],
       [ 4143,  7418]])

In [ ]:
#Create a boolean mask that identifies values in the matrix greater than 50.

In [136]:
x > 50

array([[False, False, False,  True,  True],
       [ True, False, False, False, False]])

In [ ]:
#Count the number of values in the matrix that are divisible by 5.

In [135]:
divisible_by_5_mask = x % 5 == 0

count = np.count_nonzero(divisible_by_5_mask)

print(count)

2
